### ISSUE TITLE
Your project is duplicating data

### ISSUE THREAD

**Issue by guilhermejp8** [startingwithseleniumwebdriver/RealTimeReport#11]
Hi my friend, your project is duplicating the data, it calls twice the method onTestSuccess , onTestFailure, onTestSkipped .... I need your help. Do you have any solutions?

**Comment by sureshdubey** [comment]
me too facing same issue. Pass % is showing as 200%.
Could you please correct it at your end and upload the changes.

![image](https://cloud.githubusercontent.com/assets/16201956/25846722/86c313c8-34d0-11e7-9291-d20d3a90f7f6.png)

**Comment by startingwithseleniumwebdriver** [comment]
We are unable to reproduce this issue from our end can anyone(@guilhermejp8, @sureshdubey ) please share your sample project.

**Comment by kmehta30** [comment]
@startingwithseleniumwebdriver   I am also facing the same issue of getting 200% pass. Any solution for this..
![image](https://user-images.githubusercontent.com/12829098/41051445-bb7a6514-69e8-11e8-93ca-a5491302ce28.png)

**Comment by rathodamol** [comment]
Do you have any update on the said issue.
By the way I am using the BaseTest class which is extended to all the Test Cases

**Comment by startingwithseleniumwebdriver** [comment]
The completed percentage is coming more than 100%. The problem was - TestNG captures the excluded `@test` methods list which are not really excluded by user, they are the configuration methods (i.e @BeforeTest etc..). So, now an extra check is applied from our code end to verify whether the `excluded` methods reported by TestNG is `@test` annotated method or not.

And sorry for the delay for the fix - as we could not reproduce the issue. So closing the issue.
